[project]
name = "flaskr"
version = "1.0.0"
description = "The ASD Manager app built on top of Flask"
dependencies = [
    "flask",
    "alembic"
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"